# Generated by Django 3.2.13 on 2022-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recetas'),
        ),
    ]
